/* 
The following script contains queries to understand basic business questions like total sales or total orders by customer or country.
(measures by dimensions)
This is part of the EDA data analysis project
*/
================================================
-- Find total customers by countries
================================================
select country,
COUNT(DISTINCT customer_id) AS TotalCustomers
 FROM gold.dim_customers 
GROUP BY country
ORDER BY TotalCustomers DESC;
================================================
-- Find total customers by gender
================================================
SELECT 
gender,
COUNT (customer_id)AS TotalCustomers
FROM gold.dim_customers
GROUP BY gender 
ORDER BY TotalCustomers DESC;
-- Find total products by category
SELECT 
category,
COUNT (product_key)AS TotalProducts
FROM gold.dim_products
GROUP BY  category
ORDER BY TotalProducts DESC;
================================================
-- What is the average costs in each category?
================================================
SELECT 
category,
AVG(CAST(cost AS int))AS AvgCost
FROM gold.dim_products
GROUP BY  category
ORDER BY AvgCost DESC;
================================================
-- What is the total revenue generated for each category?
================================================
SELECT 
p.category,
SUM(f.sales_amount) AS TotalRevenue
FROM gold.fact_sales f
left JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY TotalRevenue DESC;
================================================
-- Find total revenue is generated by each customer
================================================
SELECT 
c.customer_id,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS TotalRevenue
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_id = c.customer_id
GROUP BY
c.customer_id,
c.first_name,
c.last_name
ORDER BY TotalRevenue DESC;
================================================
-- What is the distribution of sold items across countries?
================================================
SELECT 
c.country,
SUM(f.quantity) AS TotalQuantity
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_id = c.customer_id
GROUP BY
c.country
ORDER BY TotalQuantity DESC;

================================================
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p 
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC

================================================
SELECT *
FROM 
(
SELECT
p.product_name,
SUM(f.sales_amount) AS total_revenue,
RANK() OVER(ORDER BY SUM(f.sales_amount)DESC) AS rank_products
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p 
ON f.product_key = p.product_key
GROUP BY p.product_name
)t 
WHERE rank_products <= 5;
================================================
SELECT TOP 10
c.customer_id,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS TotalRevenue
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_id = c.customer_id
GROUP BY
c.customer_id,
c.first_name,
c.last_name
ORDER BY TotalRevenue DESC;
